# Site settings
title: David's Jekyll Site
email: david@davidkanter.com 
description: > # this means to ignore newlines until "baseurl:"
  Someday, will Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://media.davidkanter.com" # the base hostname & protocol for your site
twitter_username: dmkanter 
github_username: dmkanter

# Build settings
markdown: kramdown
