# Permalinks
permalink:           pretty

# Setup
title:               La La Land
tagline:             where the rubber meets the road
url:                 http://example.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              La La Land
  url:               https://twitter.com/therealdeal
  email:             figureitout@gmaill.com 

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/example/broken.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
